#! /bin/sh

. "${srcdir=.}/init.sh"; path_prepend_ $exedir

fail=0
test_name="match"

# basic literal string matches
input="Hello, world"
pattern="Hello"
expected="Hello, world"
match_test "$input" "$pattern" "$expected" "${test_name} 1"

# basic literal string multiline matches
input="Hello,\n world"
pattern="Hello"
expected="Hello,"
match_test "$input" "$pattern" "$expected" "${test_name} 2"

# anchor matches
input="Hello, world"
pattern="^world"
expected=""
match_test "$input" "$pattern" "$expected" "${test_name} 3"

exit $fail