#! /bin/sh

. "${srcdir=.}/init.sh"; path_prepend_ $exedir

fail=0
test_name="status"

# empty input
input=""
pattern=""
status=0
status_test "$input" "$pattern" $status "${test_name} 1"

out=$(grep "" /dev/null)
if test $? -ne 1 ; then
  echo "Status: Wrong status code, test \#2 failed"
  fail=1
fi

# non-empty input

# should return 0 found a match
input="abcd"
pattern="abcd"
status=0
status_test "$input" "$pattern" $status "${test_name} 3"

# should return 1 found no match
input="abcd"
pattern="1234"
status=1
status_test "$input" "$pattern" $status "${test_name} 4"

# should return 2 syntax error
input="abcd"
pattern="[:lower:"
status=2
status_test "$input" "$pattern" $status "${test_name} 5"

# should return 2 inaccessible files
# out=$(grep "abcd" none-existent-file.txt)
# if test $? -ne 2 ; then
#   echo "Status: Wrong status code, test \#9 failed"
#   fail=1
# fi

exit $fail